version: '3'
services:
    mariadb:
        container_name: mariadb
        privileged: true
        build: ./mariadb
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/data/mysql
            - "./mariadb/conf/my.cnf:/etc/mysql/my.cnf"
            - "./mariadb/etc/supervisor:/etc/supervisor"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        networks:
            - app_net
    php-fpm7:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile7
        volumes:
            - ./php-fpm/etc7/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./php-fpm/etc7/php-fpm.d/:/usr/local/etc/php-fpm.d
            - ./php-fpm/etc7/php/php7.ini:/usr/local/etc/php/php.ini
            - ./php-fpm/etc/supervisor:/etc/supervisor
            - ${WORK_DIR}:/data
            - ${LOG_DIR}/php:/phplogs
        ports:
            - "2225:22"
    php-fpm5:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile55
        container_name: php-fpm5
        privileged: true
        volumes:
            - ./php-fpm/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./php-fpm/etc/php-fpm.d/:/usr/local/etc/php-fpm.d
            - ./php-fpm/etc/php/php55.ini:/usr/local/etc/php/php.ini
            - ./php-fpm/etc/supervisor:/etc/supervisor
            - ${WORK_DIR}:/data
            - ${LOG_DIR}/php:/phplogs
        depends_on:
            #- workspace
            - mariadb
        ports:
            - "2224:22"
        networks:
            - app_net
    nginx:
        build: ./nginx
        privileged: true
        container_name: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/mingyuan.d:/etc/nginx/mingyuan.d
            - ${LOG_DIR}/nginx/:/wwwlogs/
            - ./nginx/etc/supervisor:/etc/supervisor
            - ${WORK_DIR}:/data
        ports:
            - ${NGINX_PORT}
            - "443:443"
        networks:
            - app_net
    redis:
        ports:
            - "6379:6379"
        container_name: redis
        privileged: true
        build: ./redis
        networks:
            - app_net
    mongo:
        build: ./mongo
        container_name: mongo
        networks:
            - app_net
    zookeeper:
        build: ./zookeeper
        container_name: zookeeper
        networks:
            - app_net
    elasticsearch:
        build: ./elasticsearch
        container_name: elasticsearch
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - node.master=true
            - node.name=master
            - path.logs=/usr/share/elasticsearch/logs
            - xpack.ml.enabled=true
        networks:
            - app_net
        volumes:
            - ./elasticsearch/esdata1:/usr/share/elasticsearch/data
            - ./elasticsearch/jvm.options:/etc/elasticsearch/jvm.options
            - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./elasticsearch/logs:/usr/share/elasticsearch/logs
        ports:
            - "9200:9200"
            - "9300:9300"
        ulimits:
            memlock:
                soft: -1
                hard: -1
    logstash:
        build: ./logstash
        container_name: logstash
        privileged: true
        networks:
            - app_net
        links:
            - elasticsearch
        volumes:
            - ./logstash/logstash.conf:/logstash.conf
            - ./logstash/logstash.yml:/etc/logstash/logstash.yml
            - ./logstash/patterns:/patterns
        ports:
            - "5044:5044"
    kibana:
        build: ./kibana
        container_name: kibana
        privileged: true
        networks:
            - app_net
        links:
            - elasticsearch
        ports:
            - "5601:5601"
    node:
        build: ./node
        container_name: node
        privileged: true
        networks:
        - app_net
        volumes:
        - ./node/etc/supervisor:/etc/supervisor
        - ${WORK_DIR}:/data
    kafka:
        build: ./kafka
        container_name: kafka
        privileged: true
        networks:
        - app_net
        volumes:
        - ${WORK_DIR}:/data
networks:
    app_net:
        external: true

volumes:
    mysql-data:
