version: '3'
services:
        apps:
                container_name: apps
                privileged: true
                build: ./apps
                volumes:
                - ./apps:/www
                networks:
                - app_net
        mariadb:
                container_name: mariadb
                privileged: true
                build: ./mariadb
                ports:
                - "3306:3306"
                environment:
                - MYSQL_ROOT_PASSWORD=123456
                networks:
                - app_net
        php-fpm:
                build: ./php-fpm
                container_name: php-fpm
                privileged: true
                volumes:
                - ./php-fpm/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
                - ./php-fpm/etc/php-fpm.d/:/usr/local/etc/php-fpm.d
                - ./php-fpm/logs/:/phplogs/
                - ./apps:/www
                links:
                - apps
                ports:
                - "9000:9000"
                networks:
                - app_net
        nginx:
                build: ./nginx
                privileged: true
                container_name: nginx
                volumes:
                - ./nginx/nginx.conf:/etc/nginx/nginx.conf
                - ./nginx/conf.d:/etc/nginx/conf.d
                - ./nginx/logs:/wwwlogs/
                - ./apps:/www
                ports:
                - "80:80"
                depends_on:
                - php-fpm
                links:
                - php-fpm
                networks:
                - app_net
        #extra_hosts:
        #            - "php-fpm:192.168.99.1"
        redis:
                ports:
                - "6379:6379"
                container_name: redis 
                privileged: true
                build: redis
                networks:
                - app_net
networks:
        app_net:
                external: true
