version: '3'
services:
        mariadb:
                container_name: mariadb
                privileged: true
                build: mariadb
                ports:
                - "3306:3306"
                environment:
                - MYSQL_ROOT_PASSWORD=123456
        php-fpm:
                build: ./php-fpm
                container_name: php-fpm
                privileged: true
                volumes:
                - /data/php-fpm/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
                - /data/php-fpm/etc/php-fpm.d/:/usr/local/etc/php-fpm.d
                - /data/php-fpm/logs/:/phplogs/
                - /www:/www
                ports:
                - "9000:9000"
        nginx:
                build: ./nginx
                privileged: true
                volumes:
                - /data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
                - /data/nginx/conf/conf.d:/etc/nginx/conf.d
                - /data/nginx/logs:/wwwlogs/
                - /www:/www
                ports:
                - "80:80"
                links:
                - php-fpm 
        redis:   
                ports:
                - "6379:6379"
                container_name: redis 
                privileged: true
                build: redis
