version: '3'
services:
        apps:
                container_name: apps
                privileged: true
                build: ./apps
                volumes:
                - ./apps:/www
                networks:
                - app_net
                
        mariadb:
                container_name: mariadb
                privileged: true
                build: ./mariadb
                ports:
                - "3306:3306"
                environment:
                - MYSQL_ROOT_PASSWORD=123456
                networks:
                - app_net
        php-fpm:
                build: ./php-fpm
                container_name: php-fpm
                privileged: true
                volumes:
                - ./php-fpm/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
                - ./php-fpm/etc/php-fpm.d/:/usr/local/etc/php-fpm.d
                - ./php-fpm/logs/:/phplogs/
                - ./apps:/www
                links:
                - apps
                ports:
                - "9000:9000"
                networks:
                - app_net
        nginx:
                build: ./nginx
                privileged: true
                container_name: nginx
                volumes:
                - ./nginx/nginx.conf:/etc/nginx/nginx.conf
                - ./nginx/conf.d:/etc/nginx/conf.d
                - ./nginx/logs:/wwwlogs/
                - ./apps:/www
                ports:
                - "80:80"
                depends_on:
                - php-fpm
                links:
                - php-fpm
                networks:
                - app_net
        redis:
                ports:
                - "6379:6379"
                container_name: redis 
                privileged: true
                build: ./redis
                networks:
                - app_net
        elasticsearch:
                build: ./elasticsearch
                container_name: elasticsearch
                environment:
                - cluster.name=docker-cluster
                - bootstrap.memory_lock=true
                networks:
                - app_net
                volumes:
                - ./elasticsearch/esdata1:/usr/share/elasticsearch/data
                - ./elasticsearch/jvm.options:/etc/elasticsearch/jvm.options
                - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
                ports:
                - "9200:9200"
                - "9300:9300"
                ulimits:
                    memlock:
                        soft: -1
                        hard: -1
                    nofile:
                        soft: 262144
                        hard: 262144
        
        elasticsearch1:
                build: ./elasticsearch
                container_name: elasticsearch1
                environment:
                - cluster.name=docker-cluster
                - bootstrap.memory_lock=true
                networks:
                - app_net
                volumes:
                - ./elasticsearch/esdata2:/usr/share/elasticsearch/data
                - ./elasticsearch/jvm.options:/etc/elasticsearch/jvm.options
                  # - ./elasticsearch/jvm.options:/user/share/elasticsearch/config/jvm.options
                - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
                  #- ./elasticsearch/elasticsearch.yml:/etc/elasticseach/elasticsearch.yml
                ports:
                - "9201:9200"
                - "9301:9300"
                ulimits:
                    memlock:
                        soft: -1
                        hard: -1
                    nofile:
                        soft: 65536
                        hard: 65536
        
        logstash:
                build: ./logstash
                container_name: logstash
                privileged: true
                networks:
                - app_net
                links:
                - elasticsearch
                volumes:
                - ./logstash/logstash.conf:/logstash.conf
                - ./logstash/logstash.yml:/etc/logstash/logstash.yml
                - ./logstash/patterns:/patterns
                ports:
                - "5044:5044"
                links:
                - elasticsearch
        kibana:
                build: ./kibana
                container_name: kibana
                privileged: true
                networks:
                - app_net
                links:
                - elasticsearch
                ports:
                - "5601:5601"
networks:
        app_net:
                external: true
