version: '3'
services:
    mariadb:
        container_name: mariadb
        privileged: true
        build: ./mariadb
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/data/mysql
            - "./mariadb/conf/my.cnf:/etc/mysql/my.cnf"
            - "./mariadb/etc/supervisor:/etc/supervisor"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        networks:
            - app_net
    php-fpm:
        image: registry.cn-shenzhen.aliyuncs.com/canbefree/php-fpm:v1.0.2
        container_name: php-fpm
        privileged: true
        volumes:
            - ./php-fpm/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./php-fpm/etc/php-fpm.d/:/usr/local/etc/php-fpm.d
            - ./php-fpm/etc/php/php.ini:/usr/local/etc/php/php.ini
            - ./php-fpm/etc/supervisor:/etc/supervisor
            - ${WORK_DIR}:/data
            - ${LOG_DIR}/php:/phplogs
        depends_on:
            #- workspace
            - mariadb
        ports:
            - "9100:9000"
            - "2223:22"
            - "9601:9601"
            - "9501:9501"
            - "9801-9899:9801-9899"
        networks:
            - app_net
    php-fpm5:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile55
        container_name: php-fpm5
        privileged: true
        volumes:
            - ./php-fpm/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./php-fpm/etc/php-fpm.d/:/usr/local/etc/php-fpm.d
            - ./php-fpm/etc/php/php55.ini:/usr/local/etc/php/php.ini
            - ./php-fpm/etc/supervisor:/etc/supervisor
            - ${WORK_DIR}:/data
            - ${LOG_DIR}/php:/phplogs
        depends_on:
            #- workspace
            - mariadb
        ports:
            - "2224:22"
        networks:
            - app_net
    nginx:
        image: registry.cn-shenzhen.aliyuncs.com/canbefree/nginx:v1.0.0
        privileged: true
        container_name: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ${LOG_DIR}/nginx/:/wwwlogs/
            - ./nginx/etc/supervisor:/etc/supervisor
            - ${WORK_DIR}:/data
        ports:
            - "80-99:80-99"
        depends_on:
            - php-fpm
              #- workspace
#        links:
#            - php-fpm
        networks:
            - app_net
    redis:
        ports:
            - "6379:6379"
        container_name: redis
        privileged: true
        build: ./redis
        networks:
            - app_net
    mongo:
        build: ./mongo
        container_name: mongo
        networks:
            - app_net
    zookeeper:
        build: ./zookeeper
        container_name: zookeeper
        networks:
            - app_net
    elasticsearch:
        build: ./elasticsearch
        container_name: elasticsearch
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - node.master=true
            - node.name=master
            - path.logs=/usr/share/elasticsearch/logs
            - xpack.ml.enabled=true
        networks:
            - app_net
        volumes:
            - ./elasticsearch/esdata1:/usr/share/elasticsearch/data
            - ./elasticsearch/jvm.options:/etc/elasticsearch/jvm.options
            - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./elasticsearch/logs:/usr/share/elasticsearch/logs
        ports:
            - "9200:9200"
            - "9300:9300"
        ulimits:
            memlock:
                soft: -1
                hard: -1
    logstash:
        build: ./logstash
        container_name: logstash
        privileged: true
        networks:
            - app_net
        links:
            - elasticsearch
        volumes:
            - ./logstash/logstash.conf:/logstash.conf
            - ./logstash/logstash.yml:/etc/logstash/logstash.yml
            - ./logstash/patterns:/patterns
        ports:
            - "5044:5044"
        links:
            - elasticsearch
    kibana:
        build: ./kibana
        container_name: kibana
        privileged: true
        networks:
            - app_net
        links:
            - elasticsearch
        ports:
            - "5601:5601"

    c0:
        image: registry.cn-shenzhen.aliyuncs.com/canbefree/consul:1.0.1
        container_name: c0
        privileged: true
        networks:
            - app_net
        volumes:
            - ./consul/c0/etc/supervisord.d:/etc/supervisor/conf.d
            - ./consul/c0/etc/consul.d:/etc/consul.d
            - ${WORK_DIR}:/data
        ports:
            - "10220:22"
            - "7100:7100"
            - "8500:8500"
            - "8600:8600"

    c1:
        image: registry.cn-shenzhen.aliyuncs.com/canbefree/consul:1.0.1
        container_name: c1
        privileged: true
        networks:
        - app_net
        volumes:
        - ./consul/c0/etc/supervisord.d:/etc/supervisor/conf.d
        - ./consul/c1/etc/consul.d:/etc/consul.d
        - ${WORK_DIR}:/data
        ports:
        - "10221:22"
        - "7101:7100"
        - "8501:8500"
        - "8601:8600"
    c2:
        image: registry.cn-shenzhen.aliyuncs.com/canbefree/consul:1.0.1
        container_name: c2
        privileged: true
        networks:
        - app_net
        volumes:
        - ./consul/c0/etc/supervisord.d:/etc/supervisor/conf.d
        - ./consul/c2/etc/consul.d:/etc/consul.d
        - ${WORK_DIR}:/data
        ports:
        - "10222:22"
        - "7102:7100"
        - "8502:8500"

    node:
        build: ./node
        container_name: node
        privileged: true
        networks:
        - app_net
        volumes:
        - ./node/etc/supervisor:/etc/supervisor
        - ${WORK_DIR}:/data

networks:
    app_net:
        external: true

volumes:
    mysql-data:
